### PR TITLE
Switched to reading our files from S3

### PR DESCRIPTION
**Pull request by acorncom**
Pending CORS headers being set on our bucket, this should allow this to read from our S3 bucket out of the box

### CODE REVIEW

**Comment by acorncom** [comment]
@sivakumar-kailasam Done

**Comment by acorncom** [comment]
Fixes https://github.com/ember-learn/ember-api-docs/issues/157 as well

**Comment by sivakumar-kailasam** [comment]
Ah just one more file change, https://github.com/ember-learn/ember-api-docs/blob/master/.travis.yml#L26. So that travis will work going forward for PRs

**Comment by sivakumar-kailasam** [comment]
Holding on to this until https://github.com/ember-learn/ember-jsonapi-docs/pull/28 is merged

**Pull request merged**
