### PR TITLE
Algolia Search integration

### PR DESCRIPTION
**Pull request by toddjordan**

### CODE REVIEW

**Comment by toddjordan** [comment]
@mschinis and I identified a link-to issue that needs to get fix before deployment.  Will try to get this in asap before we merge

**Comment by mschinis** [comment]
I will also be pitching in over the weekend to:
- Remove private methods from showing up
- Display classes that match the search query to the top of the results.

**Comment by mschinis** [comment]
🎉

**Comment by acorncom** [comment]
Indeed 🎉

**Pull request merged**
