### PR TITLE
set yarn policy

### PR DESCRIPTION
**Pull request by Gaurav0**
Ran `yarn set version 1.22.4` and committed the result.

### CODE REVIEW

**Comment by Gaurav0** [comment]
It's not recommended to use one version of yarn to install another.

**Comment by sivakumar-kailasam** [comment]
https://classic.yarnpkg.com/en/docs/package-json#toc-engines I was referring to this

**Comment by Gaurav0** [comment]
I think that will just cause yarn install to fail if it doesn't match?

**Comment by sivakumar-kailasam** [comment]
That’s true but Heroku uses that field to determine which version of yarn to use.

**Pull request closed without merging**
