### PR TITLE
Adds module/package import intro and links to commonly searched-for docs

### PR DESCRIPTION
**Pull request by jaredgalanis**
Installs ember-prism addon for code highlighting.

Adds some styling for prism.js.

Adds links to commonly searched-for documentation.

Adds content for intro of new module/package import syntax.

@jenweber

### CODE REVIEW

**Comment by jaredgalanis** [comment]
The fix for the linting error needs attention. Prism is doing something funky with the indentation of the first line.

**Comment by jaredgalanis** [comment]
Hey @toddjordan, yeah I'll include some a little later. The current thinking is actually revised a little after I learned how prism is going to be used in the guides/deprecations apps that are forthcoming.

**Comment by jaredgalanis** [comment]
@toddjordan, this is how it's currently looking:

screen shot 2018-02-13 at 8 01 11 pm

**Comment by jenweber** [comment]
This is a merge into a WIP feature branch, not master. Merged.

**Pull request merged**
