### PR TITLE
Fix search input

### LINKED ISSUE #55: Add in the Algolia search box
It doesn't currently show up in the header but should

### PR DESCRIPTION
**Pull request by mschinis**
### Action points
- [x] Display API results
- [x] Display group label

Closes #55

### CODE REVIEW

**Comment by mschinis** [comment]
@acorncom For some reason the API section isn't being indexed at all by Algolia.

**Comment by acorncom** [comment]
@mschinis At this point it looks like we're set here

**Comment by mschinis** [comment]
@acorncom good to go!

**Comment by acorncom** [comment]
Thanks @mschinis !

**Pull request merged**
