### PR TITLE
[WIP] Rename /modules to /packages (#285)

### PR DESCRIPTION
**Pull request by amyrlam**
Resolves: #285

### CODE REVIEW

**Comment by amyrlam** [comment]
very WIP:

- not sure about failing tests

- want to have /modules/* manual input in url bar redirect to /packages/*, not sure how given that it's not a `beforeModel`

- getting this strange error, ideas?

```alam@tesla ember-api-docs (amy/module-package-taketwo) $ ember serve
Warning: failed to stat /Users/alam/src/ember-api-docs/tmp/broccoli_merge_trees-input_base_path-7W5XmxWe.tmp/0/ember-api-docs/controllers/project-version/packages/package/events.js
```

**Comment by jenweber** [comment]
@amyrlam 
I see the "warning: failed to stat..." error all the time. I think it's safe to ignore for the scope of this.

I resolved a test failure for "lists all subpackages on the package page" by changing line 28:
`let numberSubModules = Object.keys(container.get('submodules')).length;` Submodules should be plural.

Here's one possible way to keep routes like "modules" around. As time goes on, we'll accumulate more of these urls that we need to support. You could create a wildcard in the router like `this.route('catch-all', { path: '*:' });`. Then in the catch-all, handle exceptions like modules/packages:
```
import Ember from 'ember';

export default Ember.Route.extend({
  beforeModel(transition) {
    let intended = transition.intent.url
    if (intended.match(/modules/i)) {
      let repaired = intended.replace('modules', 'packages')
      this.replaceWith(repaired)
    } else {
      this.transitionTo('404')
    }
  }
});
```

@sivakumar-kailasam @toddjordan what do you think about having a catch all route in the api docs?

**Comment by jenweber** [comment]
Cc @locks regarding wildcard routes as a way to handle legacy urls. What do you think?

**Comment by amyrlam** [comment]
@jenweber heya, thanks for the feedback. please keep it coming! 

i'm just getting back from a ~2wk vacation with almost no interweb access. will revisit this PR friday/this weekend

**Comment by jenweber** [comment]
@amyrlam learning team feedback on my idea above is, wildcard routes can be messy and we shouldn't use them for this case.

In order to support both `/packages` and `/models` routes, the suggestion from the learning team chat is that the app should have 2 routes, one for packages and one for models. The only job of /modules will be to redirect. So the router would look something like 

```
    this.route('packages', {path: '/packages'}, function() {
      this.route('module', {path: '/:module'}, itemRoutes);
    });
    this.route('modules')
```

The `/:module` dynamic segment can stay the same, since it's internal.

Does that make sense? I wasn't quite sure what you meant when you mentioned some issues with beforeModel in your comment above, and I haven't really dug into the routing structure of the app much myself. I think you can possibly use the `redirect` hook to catch the full intended transition.

**Comment by toddjordan** [comment]
Thanks so much for this work, but we took a simpler approach by just renaming the labels and not changing our internal references.  That way if we change our minds back it won't be a big deal :-P

**Pull request closed without merging**
