### PR TITLE
Modules refactor

### PR DESCRIPTION
**Pull request by acorncom**

### CODE REVIEW

**Comment by acorncom** [comment]
Applies the https://github.com/ember-cli/ember-modules-codemod  Do we want to apply this or wait until 2.16 lands? /cc @locks 

I'm inclined to use it as we can use this app to help teach folks about how to make the change ...

**Comment by sivakumar-kailasam** [comment]
@acorncom there's a eslint config to ensure that direct ember imports would cause eslint failures. We should probably add it along with this PR. @Turbo87 might be aware of it.

**Comment by Turbo87** [comment]
> there's a eslint config to ensure that direct ember imports would cause eslint failures

the rule only warns about usage of the old shims from `ember-cli-shims` but it does not warn about `import Ember from 'ember'` yet because there are still legitimate use cases for that (e.g. `Ember.testing`).

> We should probably add it along with this PR

seems like a somewhat unrelated change and should be done in a separate PR to not block this one

**Comment by acorncom** [comment]
@Turbo87 I pushed a few buttons, it's really easy to do 😀 Thanks for all your work on that ...

**Comment by locks** [comment]
Oops, I also just pushed a couple of buttons. Nice work!

**Pull request merged**
