### PR TITLE
Replace link-to component with href-to helper

### PR DESCRIPTION
**Pull request by MartinMalinda**
This replaces `link-to` with `href-to`. 
It provides roughly 40% decrease in rendering time on `api-beta/ember/2.13.3/namespaces/Ember`.

Not that noticeable on initial load, but it is noticeable on further transitions

relates to #246

### CODE REVIEW

**Comment by toddjordan** [comment]
@MartinMalinda can you look at clearing conflicts?

**Comment by MartinMalinda** [comment]
@toddjordan I'm resolving #239 atm. I will resolve conflicts here after that's merged - it will introduce more conflicts probably.

**Comment by locks** [comment]
@MartinMalinda could we use the router service instead?

**Comment by MartinMalinda** [comment]
@locks I am not sure what you mean, this PR uses the router service

**Comment by locks** [comment]
@MartinMalinda I meant making our own `href-to` that uses the Router service, but it's fine to land this and iterate.
Are you able to fix the conflicts?

**Comment by MartinMalinda** [comment]
@locks I see. I am looking into the router service more now and I most likely get rid of some logic and use it more.

We could use the service to generate URLs and to apply `active` class on links but without `href-to` there would be no global handling of clicking the links, so we'd have to probably have `onclick` on every link.

I'll resolve conflicts here and refactor a bit once #239 is merged so I don't have to resolve twice.

**Comment by MartinMalinda** [comment]
I think `ember-href-to` will probably use the router service soon anyway.

**Comment by mschinis** [comment]
@MartinMalinda Be careful with this approach as algolia is using the `active` class on each link to identify the current link. Check out my PR description here:

https://github.com/ember-learn/ember-api-docs/issues/220

**Comment by MartinMalinda** [comment]
@mschinis I've added logic to add the `active` class on links but I will definitely double checks things are working correctly and maybe add some test coverage if there isn't already any.

Using the `isActive` function from the router service will possibly further make it error-proof

**Comment by acorncom** [comment]
One question here re replacing `link-to`. I appreciate the idea of increased speed (Id love to see things go faster). How does that play in with our idea of the API docs being a canonical reference app that represents Ember best practices? Seems a bit strange to hold it up as a good example but then also be swapping out link-to ... :grinning: Thoughts?

**Comment by MartinMalinda** [comment]
I think by providing the official `Router` service, which @locks recommends above, the things are changing a little bit.

The service provides a function for URL generation, provides an `isActive` class, the only missing piece is handling clicks on such links. `Ember-href-to` uses a global event listener for that, but a regular `action` could be used.

```
{{#with (get-url 'foo.bar' someModel) as |url|}}
<a href={{url}} class={{if (is-active url) "active"}} {{action (transition url)}}>My link</a>
{{/with}}
```

It's more verbose but also more explicit.

**Comment by MartinMalinda** [comment]
I could also adjust this PR a bit, using `https://github.com/rwjblue/ember-router-helpers`. It now provides a `route-params` helper. Usage is like so

```{{#with (route-params 'parent.child') as |routeParams|}}
      <a href="{{routeParams.url}}" class="{{if routeParams.isActive 'active' 'inactive'}}">Blah</a>
    {{/with}}

**Comment by toddjordan** [comment]
Rendering is much improved in newer Embers, and our app performance isn't bad, so putting this one on ice until rendering performance becomes more of a pressing need.  Thanks for the work and may pull this back up eventually.

**Pull request closed without merging**
