### PR TITLE
styles(tabs): Restyle tabs

### PR DESCRIPTION
**Pull request by knownasilya**
Current Tabs:

tabs-current

New Tabs:

tabs-new

### CODE REVIEW

**Comment by knownasilya** [comment]
High-quality screenshot

screen shot 2017-08-02 at 10 24 04 am

**Comment by toddjordan** [comment]
not bad

**Comment by sivakumar-kailasam** [comment]
not bad

**Comment by knownasilya** [comment]
Lol, thanks guys.

**Pull request merged**
