### PR TITLE
Consolidate namespace routes to the classes route

### PR DESCRIPTION
**Pull request by toddjordan**
Addresses #96 by making the linking behavior the same as it currently is at https://emberjs.com/api

In a submodule, classes and namespaces will now show up in a common, sorted section called "Classes and Namespaces" (as opposed to separate sections as previously)

image

Current App:
image

_(in our new version its at least sorted)_

All classes and namespaces will be addressable under /ember/<version>/classes/<class name>, both from submodule details, and from the left nav.

To support separation of classes and namespaces, we'll need to do some work on how namespaces and classes are identified within a submodule in the yuidoc, likely requiring changes to the ember code documentation.  This is a bit bigger issue than what we want to tackle at this point, so the decision was made in the last learn team meeting to go for the same routing behavior as what is already there, that being all classes and namespaces routable under 'classes'.

### CODE REVIEW

**Comment by Gaurav0** [comment]
I really don't like having "Classes and Namespaces". I thought we discussed instead having /namespace/* redirect to /class/* if it doesn't find a namespace but does find a class?

**Comment by toddjordan** [comment]
The problem goes beyond the url.  Ember right now can't accurately differentiate between a class and a namespace in regard to their relationship to a submodule.  The issue has some explanation.

"Classes and Namespaces" are what the api has currently.  Not saying we'll never make this better. Just saying that to make it better will require a bigger effort than what we want to spend to get this out the door for an MVP.  I can create an issue and assign it for the next iteration of this app.

**Comment by Gaurav0** [comment]
Am I missing some of your changed files? I pulled your branch and don't see "Classes and Namespaces" section

**Comment by toddjordan** [comment]
did something get cached?  Notice in the Changed files that we updated module.hbs.  

In the UI, just click on one of the modules, such as `ember-glitter` on the left nav.

**Comment by Gaurav0** [comment]
Ok. Misunderstood. I thought the side navbar would show classes and namespaces.

LGTM.

**Pull request merged**
