### PR TITLE
[RFC] Implements algolia search-input

### LINKED ISSUE #55: Add in the Algolia search box
It doesn't currently show up in the header but should

### PR DESCRIPTION
**Pull request by mschinis**
Fixes #55 

- [x] Setup Algolia search
- [x] Group results per section
- [x] Display results
- [x] Style dropdown
- [x] Deduplicate results by the combination of lvl0-lvl1 hierarchies
- [x] Replace triple bracket usages in templates with `html-safe` helper

### CODE REVIEW

**Comment by toddjordan** [comment]
Looks close!

**Comment by mschinis** [comment]
@toddjordan almost! One small thing left and some conflict resolving and we're good to go.
Opened https://github.com/ember-learn/ember-api-docs/issues/176 as something we might want to consider after this is finished.

**Comment by mschinis** [comment]
@toddjordan Good to go. Let me know what you think, I can do some final tweaking

**Comment by mschinis** [comment]
ugh I believe the template linting errors are failing the tests, but i can't remove the triple brackets because of the algolia query highlighting.

**Comment by acorncom** [comment]
Nice work here @mschinis

**Pull request merged**
