### PR TITLE
Update class field description component to glimmer

### PR DESCRIPTION
**Pull request by geneukum**
Let's update the ClassFieldDescription  component to extend glimmer/component instead of ember/component. Glimmer components offer a bunch of various advantages over classic components and are the direction that ember is
heading in general.

While we're here, let's prefer single quotes to double quotes throughout our template file.

Finally, let's make sure that we're using angle bracket syntax rather than curly brace syntax to invoke the component in our tests as this cleans up some deprecations logged when the tests are run.

This should resolve the app/component/class-field-description.js section of https://github.com/ember-learn/ember-api-docs/issues/805.

### CODE REVIEW

**Comment by jenweber** [comment]
Hi @geneukum! Thank you so much for these improvements. It will take me a bit of time to go through them and review. I'll aim to do that one at a time over the next week or so. Modernizing this app is a big help, as we are about to try and add some more features to it over the next year to support TypeScript examples.

**Review by jenweber — APPROVED** [review]

**Comment by geneukum** [comment]
> Hi @geneukum! Thank you so much for these improvements.

Absolutely! I'm happy to help however I can. 😄 

> It will take me a bit of time to go through them and review. I'll aim to do that one at a time over the next week or so.

That sounds great! Thanks so much for taking a look.

> Modernizing this app is a big help, as we are about to try and add some more features to it over the next year to support TypeScript examples.

Speaking of TypeScript, do you think it makes sense to pull in ember-cli-typescript and start converting some of this stuff over in a follow-up issue?

**Comment by jenweber** [comment]
Good question! Let me check in with the rest of the team. Last time the learning core team discussed adding TypeScript for the front-end apps we maintain, we decided not to do it. That was before there was a dedicated TS core team though. 

The team was ok adding it to back end node apps like ember-jsonapi-docs. I’m currently rewriting that repo though so it’s not a good candidate either at this moment. When I get a little farther, I’d like to use TypeScript in it!

Please feel free to @ me if you have any questions about this app or other projects in Ember.

**Comment by geneukum** [comment]
hey @jenweber, I hope all is well! Is there any chance that we could land some of the other PRs from this set in the not too distant future? 

I would be happy to go through whatever is remaining after a few more of them are merged. If I remember correctly, I was starting to get to the point where it seemed like they would conflict with one another. 

Thanks again for all of your help!

**Pull request merged**
