### PR TITLE
WIP hacking in the new navbar (#433)

### PR DESCRIPTION
**Pull request by jenweber**
Needs work. Don't merge. I want to test this in staging before a merge due to Fastboot concerns and styling updates.

- [ ] put the nav search bar back
- [ ] get review of styling
- [ ] make sure it doesn't break fastboot (try it in staging)
- [ ] check search in staging

### CODE REVIEW

**Comment by jenweber** [comment]
I'm a little worried about the fastboot warnings I see in the console

**Comment by sivakumar-kailasam** [comment]
@jenweber I was under the impression that we're using https://github.com/ember-learn/ember-styleguide to share styles & component across apps. Isn't that the case? If not, what would it take to start doing that?

**Comment by jenweber** [comment]
@sivakumar-kailasam This was meant to be a stopgap measure until we had a component in ember-styleguide, however it's turning into too many layers of hacking. I expect to close this PR entirely following a discussion with @MelSumner

**Comment by jenweber** [comment]
Closing this, as we almost have something ready in ember-learn/ember-styleguide

**Pull request closed without merging**
