### PR TITLE
Update scroll container selector

### PR DESCRIPTION
**Pull request by MartinMalinda**
Fixes https://github.com/ember-learn/ember-api-docs/issues/305

I checked with Firefox ✅ 
Did not check with IE so far but it should work 99% (I'll check with BrowserStack if we have a PR preview URL).

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
@MartinMalinda created a review app.

**Comment by MartinMalinda** [comment]
Seems like BrowserStack does not offer free IE tests anymore. I briefly checked it on IE 11 emulator within Edge and it worked there but so did the production version.

Also, the failing test seems like some super random edge case. I tried running it several time, normally and headlessly without issues.

Can we merge and reopen if someone reports issues?

Or let someone with Windows provide feedback also after a fix for https://github.com/ember-learn/ember-api-docs/issues/304 is merged?

**Comment by sivakumar-kailasam** [comment]
@MartinMalinda tried a restart and the failure seems to be consistent. Can you try spending some time on it? If you can't get far, I can help pitch in.

**Comment by sivakumar-kailasam** [comment]
But once that's done, I'm good to merge.

**Comment by MartinMalinda** [comment]
Turns out I just haven't committed some of the last changes :) It should pass now.

**Pull request merged**
