### PR TITLE
Removing the defunct "How to import and use packages" section

### PR DESCRIPTION
**Pull request by cah-johnryan**

### CODE REVIEW

**Comment by cah-johnryan** [comment]
This is related to https://github.com/ember-learn/ember-api-docs/issues/732

**Comment by cah-johnryan** [comment]
For some reason there is an acceptance test that is failing the CI.  I will look into this later today.

```not ok 184 Chrome 86.0 - [169 ms] - Acceptance | convert legacy url to current: should convert url for legacy ember data module
    ---
        actual: >
            /404
        expected: >
            /ember-data/release/modules/@ember-data
        stack: >
                at _callee5$ (http://localhost:7357/assets/tests.js:373:24)
                at tryCatch (http://localhost:7357/assets/vendor.js:6865:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:7094:22)
                at Generator.prototype.<computed> [as next] (http://localhost:7357/assets/vendor.js:6917:21)
                at asyncGeneratorStep (http://localhost:7357/assets/tests.js:261:105)
                at _next (http://localhost:7357/assets/tests.js:263:196)
        negative: >
            false
        browser log: |
            WARN: [object Object] fetching by class or module failed, retrying as namespace
            ERROR: [object Object]
    ...```

**Comment by ijlee2** [comment]
@cah-johnryan Thanks for letting us know about the failing test. I noticed that the `master` branch failed its CI back in June, and another current pull request is failing a different test. I pinged the Learning Team to see if someone might be able to help.

**Comment by cah-johnryan** [comment]
image

**Comment by cah-johnryan** [comment]
@ijlee2, I think I found the solution for what is going on here and added a commit to this PR in relation to it.  Let me know your thoughts.

**Comment by ijlee2** [comment]
Thanks for investigating the issue! I'm not too familiar with this repo yet, sorry. @locks may look into it.

**Comment by locks** [comment]
I did some quick spelunking and I believe the change was introduced here: https://github.com/emberjs/data/commit/0e638e61bc631ad38b19e98b8bc9e6ddfcd749bc.

Could we redirect to `/ember-data/release` instead of the 404? That seems like a better experience for the reader.  
As an improvement, we could then make an index page like https://api.emberjs.com/ember/release for the Ember Data project specifically.

**Review by jenweber — APPROVED** [review]
I think that this test change is good for unblocking PRs, and we should merge this as-is. I agree with locks that what we should do is change the redirects themselves to go to the index page for Ember Data. That can be done by anybody in a separate PR though, so I'd like to merge this if that's ok.

Ticket for making a landing page:
https://github.com/ember-learn/ember-api-docs/issues/638

Ticket for fixing the redirects:
https://github.com/ember-learn/ember-api-docs/issues/735

**Comment by locks** [comment]
@jenweber sounds good! can you create an issue for the follow-up work before merging so we don't accidentally drop the work?

**Comment by jenweber** [comment]
You read my mind. Or I read yours. lol

**Pull request merged**
