### PR TITLE
Implement 404

### PR DESCRIPTION
**Pull request by MehulKChaudhari**
Fixes: #884 
Desktop version:
image

Mobile Version:
image

### CODE REVIEW

**Comment by MehulKChaudhari** [comment]
Hey @MinThaMie, Could you please review this PR?

**Comment by MinThaMie** [comment]
Hey, thanks for the work you did, I'm sorry I did not do a better job at pointing you to the right starting branch. Our website-redesign (#829) branch should be your starting point and no longer uses scss. I hope you don't mind changing that. If you do, please let me know so I can port your changes there. It looks good, on mobile I would prefer a bit of margin around the image :)

**Comment by MehulKChaudhari** [comment]
> Hey, thanks for the work you did, I'm sorry I did not do a better job at pointing you to the right starting branch. Our website-redesign (#868) branch should be your starting point and no longer uses scss. I hope you don't mind changing that. If you do, please let me know so I can port your changes there. It looks good, on mobile I would prefer a bit of margin around the image :)  

Sure no worries, I will make the changes.

**Comment by MehulKChaudhari** [comment]
looking this PR will be raising new with website-redesign as base branch

**Pull request closed without merging**
